In [5]:
import pandas as pd
df_pt1 = pd.read_csv('https://raw.githubusercontent.com/ross167/vanguard-ab-test/refs/heads/main/database/raw/df_final_web_data_pt_1.csv')
df_pt2 = pd.read_csv('https://raw.githubusercontent.com/ross167/vanguard-ab-test/refs/heads/main/database/raw/df_final_web_data_pt_2.csv')
df_pt = pd.concat([df_pt1,df_pt2])

df_pt.duplicated().sum()
df_pt = df_pt.drop_duplicates().reset_index().drop(columns="index")

In [44]:
df_exp = pd.read_csv('https://raw.githubusercontent.com/ross167/vanguard-ab-test/refs/heads/main/database/clean/df_final_experiment_clients_cleaned.csv')

df_demo = pd.read_csv('https://raw.githubusercontent.com/ross167/vanguard-ab-test/refs/heads/main/database/clean/df_final_demo.csv')

In [45]:
df_demo.drop(columns='Unnamed: 0',inplace=True)
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0
...,...,...,...,...,...,...,...,...,...
70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0
70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0
70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0
70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0
70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0

In [46]:
df_exp.drop(columns='Unnamed: 0',inplace=True)
df_exp

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

In [49]:
df_demo = df_demo.merge(df_exp, on= 'client_id', how="inner")

In [53]:
df_demo

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control
...,...,...,...,...,...,...,...,...,...,...
50495,1780858,21.0,262.0,68.5,M,3.0,372100.59,6.0,9.0,Test
50496,6967120,21.0,260.0,68.5,M,3.0,4279873.38,6.0,9.0,Control
50497,5826160,20.0,249.0,56.5,F,2.0,44837.16,2.0,5.0,Test
50498,8739285,19.0,229.0,69.5,F,2.0,44994.24,1.0,4.0,Test
50499,7468138,18.0,222.0,61.0,F,3.0,209278.15,0.0,3.0,Test

In [54]:
df_demo.rename(columns=lambda x: x.lower(), inplace=True)

In [55]:
df_pt["date_time"] = pd.to_datetime(df_pt["date_time"])

In [56]:
df = df_pt.copy()

In [ ]:
#df = df_pt.merge(df_exp, on="client_id", how="left")
#df.dropna(inplace=True)

In [57]:
step = {
    "start": 0,
    "step_1": 1,
    "step_2": 2,
    "step_3": 3,
    "confirm": 4}

In [58]:
df['process_step'] = df['process_step'].map(step)

In [59]:
df

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:18:04
...,...,...,...,...,...
744636,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:46:10
744637,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:45:29
744638,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:44:51
744639,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:44:34
744640,674799,947159805_81558194550,86152093_47511127657_716022,0,2017-06-03 12:17:09

In [60]:
df[df['client_id'].isin(df_demo['client_id'])]

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:18:04
...,...,...,...,...,...
629303,1574008,117364417_77840596075,528720790_71583064618_169151,0,2017-05-06 23:43:27
629346,2908510,814969699_90652851448,562606085_36368381773_92090,0,2017-05-10 22:57:17
629347,2908510,814969699_90652851448,562606085_36368381773_92090,2,2017-05-10 22:56:31
629348,2908510,814969699_90652851448,562606085_36368381773_92090,1,2017-05-10 22:56:23
629349,2908510,814969699_90652851448,562606085_36368381773_92090,0,2017-05-10 22:56:20

In [44]:
(df[df['client_id'] == 9988021]['process_step'] == 4).sum() == 0

np.True_

In [20]:
def check_confirm(row):
        if (df[df['client_id'] == row['client_id']]['process_step'] == 4).sum() > 0:
            return "Confirmed"
        else:
            return "Not confirmed"

In [21]:
df['confirm_status'] = df.apply(check_confirm, axis=1)

In [23]:
df1 = df.copy()

In [31]:
df1[df1['client_id'] == 9668240]

,client_id,visitor_id,visit_id,process_step,date_time,confirm_status,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
744620,9668240,388766751_9038881013,922267647_3096648104_968866,4,2017-05-24 19:07:35,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744621,9668240,388766751_9038881013,922267647_3096648104_968866,3,2017-05-24 19:05:14,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744622,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 19:05:07,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744623,9668240,388766751_9038881013,922267647_3096648104_968866,3,2017-05-24 19:04:43,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744624,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 19:04:03,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744625,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 19:04:00,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744626,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 19:02:37,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744627,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 19:02:19,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744628,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 19:02:04,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744629,9668240,388766751_9038881013,922267647_3096648104_968866,3,2017-05-24 18:51:37,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744630,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 18:51:15,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744631,9668240,388766751_9038881013,922267647_3096648104_968866,3,2017-05-24 18:51:04,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744632,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 18:49:36,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744633,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:49:35,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744634,9668240,388766751_9038881013,922267647_3096648104_968866,2,2017-05-24 18:48:11,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744635,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:48:02,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744636,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:46:10,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744637,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:45:29,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744638,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:44:51,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744639,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:44:34,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
#(t1 - t2).total_seconds()

df['date_time'].iloc[0] - df['date_time'].iloc[1]

Timedelta('0 days 00:00:16')

In [24]:
df1 = df1.merge(df_demo, on='client_id',how='left')

In [25]:
df1

,client_id,visitor_id,visit_id,process_step,date_time,confirm_status,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:27:07,Not confirmed,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:26:51,Not confirmed,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:19:22,Not confirmed,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:19:13,Not confirmed,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:18:04,Not confirmed,5.0,64.0,79.0,U,2.0,189023.86,1.0,4.0,Test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
744636,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:46:10,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744637,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:45:29,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744638,9668240,388766751_9038881013,922267647_3096648104_968866,1,2017-05-24 18:44:51,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744639,9668240,388766751_9038881013,922267647_3096648104_968866,0,2017-05-24 18:44:34,Confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744640,674799,947159805_81558194550,86152093_47511127657_716022,0,2017-06-03 12:17:09,Not confirmed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df1.isnull().sum()

client_id                0
visitor_id               0
visit_id                 0
process_step             0
date_time                0
confirm_status           0
clnt_tenure_yr      300744
clnt_tenure_mnth    300744
clnt_age            300744
gendr               300744
num_accts           300744
bal                 300744
calls_6_mnth        300744
logons_6_mnth       300744
variation           427406
dtype: int64

In [ ]:
df1.to_csv('/Users/hanguyen/Documents/DATA ANALYTICS/IRONHACK/Week 5/Project/vanguard-ab-test/database/Clean/df_confirm_status.csv')

In [51]:
df_demo

,Unnamed: 0,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
0,0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control
...,...,...,...,...,...,...,...,...,...,...,...
70604,70604,7993686,4.0,56.0,38.5,U,3.0,1411062.68,5.0,5.0,NaN
70605,70605,8981690,12.0,148.0,31.0,M,2.0,101867.07,6.0,6.0,NaN
70606,70606,333913,16.0,198.0,61.5,F,2.0,40745.00,3.0,3.0,NaN
70607,70607,1573142,21.0,255.0,68.0,M,3.0,475114.69,4.0,4.0,NaN
70608,70608,5602139,21.0,254.0,59.5,F,3.0,157498.73,7.0,7.0,NaN

In [53]:
df_demo[df_demo['client_id'] == 169]

,Unnamed: 0,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,variation
59771,59771,169,21.0,262.0,47.5,M,2.0,501570.72,4.0,4.0,NaN

In [54]:
df_new = df[['client_id', 'confirm_status']]

In [56]:
df_demo = df_demo.merge(df_new, on='client_id',how="left")

In [58]:
df_final = df_demo.copy()

In [59]:
df_final.to_csv('/Users/hanguyen/Documents/DATA ANALYTICS/IRONHACK/Week 5/Project/final.csv')

In [46]:
df_new

client_id                              9988021
visitor_id                580560515_7732621733
visit_id          781255054_21935453173_531117
process_step                                 3
date_time                  2017-04-17 15:19:22
variation                                 Test
confirm_status                   not confirmed
Name: 2, dtype: object

In [17]:
df_test = df[df['variation'] == "Test"]
df_test

,client_id,visitor_id,visit_id,process_step,date_time,variation
0,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:27:07,Test
1,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:26:51,Test
2,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:19:22,Test
3,9988021,580560515_7732621733,781255054_21935453173_531117,2,2017-04-17 15:19:13,Test
4,9988021,580560515_7732621733,781255054_21935453173_531117,3,2017-04-17 15:18:04,Test
...,...,...,...,...,...,...
629299,1574008,117364417_77840596075,528720790_71583064618_169151,4,2017-05-06 23:51:05,Test
629300,1574008,117364417_77840596075,528720790_71583064618_169151,3,2017-05-06 23:50:40,Test
629301,1574008,117364417_77840596075,528720790_71583064618_169151,2,2017-05-06 23:43:47,Test
629302,1574008,117364417_77840596075,528720790_71583064618_169151,1,2017-05-06 23:43:34,Test
629303,1574008,117364417_77840596075,528720790_71583064618_169151,0,2017-05-06 23:43:27,Test

In [93]:
df_control = df[df['variation'] == "Control"]
df_control

,client_id,visitor_id,visit_id,process_step,date_time,variation
13,4033851,762728880_76361333336,949661017_22392791362_127391,4,2017-04-05 12:29:03,Control
14,4033851,762728880_76361333336,949661017_22392791362_127391,4,2017-04-05 12:29:01,Control
15,4033851,762728880_76361333336,949661017_22392791362_127391,4,2017-04-05 12:28:52,Control
16,4033851,762728880_76361333336,949661017_22392791362_127391,3,2017-04-05 12:26:08,Control
17,4033851,762728880_76361333336,949661017_22392791362_127391,2,2017-04-05 12:24:43,Control
...,...,...,...,...,...,...
629289,433098,5505424_50616523266,773565250_67577573147_389841,0,2017-05-13 15:30:47,Control
629346,2908510,814969699_90652851448,562606085_36368381773_92090,0,2017-05-10 22:57:17,Control
629347,2908510,814969699_90652851448,562606085_36368381773_92090,2,2017-05-10 22:56:31,Control
629348,2908510,814969699_90652851448,562606085_36368381773_92090,1,2017-05-10 22:56:23,Control
629349,2908510,814969699_90652851448,562606085_36368381773_92090,0,2017-05-10 22:56:20,Control

In [ ]:
df_test[df_test['process_step'] == 4]['visitor_id'].nunique()

19505

In [ ]:
#Function that calculate the completion rate by different parameters and step

def calculate_completion_rate(param,step):
    number_of_clients_confirm_testgroup = df_test[df_test['process_step'] == step][param].nunique()
    number_of_clients_confirm_controlgroup = df_control[df_control['process_step'] == step][param].nunique()

    #Calculate the total number of visitors in each group:

    total_number_of_clients_testgroup = df_test[df_test['process_step'] == 0][param].nunique()
    total_number_of_clients_controlgroup = df_control[df_control['process_step'] == 0][param].nunique()

    #Calculate the completion rate for each group:

    completion_rate_testgroup = round((number_of_clients_confirm_testgroup / total_number_of_clients_testgroup)*100, 2)
    completion_rate_controlgroup = round((number_of_clients_confirm_controlgroup / total_number_of_clients_controlgroup)*100, 2)


    #print(f"Successful rate of step number {step} for Test group: {completion_rate_testgroup}%")
    #print(f"Successful rate of step number {step} for Control group: {completion_rate_controlgroup}%")
    #print(f"Test group has a {(conversion_rate_testgroup - conversion_rate_controlgroup):.2%} higher completion rate for step {step} than Control group counting by {parram}")

    return  completion_rate_testgroup, completion_rate_controlgroup

In [173]:
calculate_completion_rate('client_id',4)

(70.04, 65.97)

In [174]:
calculate_completion_rate('visit_id',4)

(65.54, 51.91)

In [175]:
calculate_completion_rate('client_id',1)

(90.96, 86.13)

In [176]:
#Success rate by each group count by client_id 
df_client_id = pd.DataFrame([calculate_completion_rate('client_id', step) for step in range (5)], columns=["test_group", "control_group"]).reset_index()
df_client_id  = df_client_id.rename(columns = {'index': 'step'})
df_client_id

   step  test_group  control_group
0     0      100.00         100.00
1     1       90.96          86.13
2     2       83.43          79.71
3     3       78.27          74.46
4     4       70.04          65.97

In [177]:
#Success rate by each group count by visitor_id (Each client has average 2 visitor_id)
df_visitor_id = pd.DataFrame([calculate_completion_rate('visitor_id', step) for step in range (5)], columns=["test_group", "control_group"]).reset_index()
df_visitor_id  = df_visitor_id.rename(columns = {'index': 'step'})
df_visitor_id

   step  test_group  control_group
0     0      100.00         100.00
1     1       88.93          81.96
2     2       79.96          73.97
3     3       74.02          68.31
4     4       67.88          60.08

In [178]:
df_visit_id = pd.DataFrame([calculate_completion_rate('visit_id', step) for step in range (5)], columns=["test_group", "control_group"]).reset_index()
df_visit_id = df_visit_id.rename(columns = {'index': 'step'})
df_visit_id

   step  test_group  control_group
0     0      100.00         100.00
1     1       85.31          76.18
2     2       73.90          65.15
3     3       66.91          59.20
4     4       65.54          51.91